CREATE TABLE IF NOT EXISTS HACKER_NEWS (
    HACER_NAME TEXT,
    VICTIM_NAME TEXT,
    LOST_MONEY INTEGER
);

INSERT INTO HACKER_NEWS (HACER_NAME, VICTIM_NAME, LOST_MONEY) VALUES
('STEVEN KING', 'PETER', 24000),
('NEENA', 'DANNY', 48000),
('MARKO', 'SAM', 500000),
('STEVEN', 'SUNNY', 45000),
('PANTAR', 'WIKKY', 26000)

SELECT HACER_NAME AS "Hacker Name",
SUM(LOST_MONEY) AS "Total Lost money"
FROM HACKER_NEWS
GROUP BY HACER_NAME;

SELECT HACER_NAME AS "Hacker Name",
SUM(LOST_MONEY) AS TOTAL_LOST
FROM HACKER_NEWS 
WHERE LOST_MONEY > 26000
GROUP BY HACER_NAME;